### ISSUE TITLE
mui is not defined!

### ISSUE THREAD

**Issue by Carniatto** [poetic/react-material-ui#8]
I created a new project and follow the directions on the readme.md

but when I run I got this error:

W20151117-21:10:08.466(-2)? (STDERR) ReferenceError: mui is not defined
W20151117-21:10:08.466(-2)? (STDERR)     at first-meteor.jsx:1:64
W20151117-21:10:08.467(-2)? (STDERR)     at /Users/carniatto/dev/material-meteor/first-meteor/.meteor/local/build/programs/server/app/first-meteor.jsx:89:4
W20151117-21:10:08.467(-2)? (STDERR)     at /Users/carniatto/dev/material-meteor/first-meteor/.meteor/local/build/programs/server/boot.js:242:10
W20151117-21:10:08.467(-2)? (STDERR)     at Array.forEach (native)
W20151117-21:10:08.468(-2)? (STDERR)     at Function._.each._.forEach (/Users/carniatto/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151117-21:10:08.468(-2)? (STDERR)     at /Users/carniatto/dev/material-meteor/first-meteor/.meteor/local/build/programs/server/boot.js:137:5

**Comment by codeNgamer** [comment]
@Carniatto so it looks like you might be trying to use mui server side. please confirm that your code block that throws that error is actually client side (i.e in a client folder or Meteor.isclient block)

**Comment by codeNgamer** [comment]
@Carniatto were you able to resolve the issue?

**Comment by Carniatto** [comment]
actually no I followed your instructions but did not work. Now I found another library that has a better explained solution. It seems that I need to insert some js files around it to export this..

**Comment by lavrimax** [comment]
@Carniatto , I have the same problem. Could you tell what library worked in your case?
